### ISSUE TITLE
Question: Why alway ignore 'mysql' database?

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-lightning#320]
## Question

Before asking a question, make sure you have:

- Searched existing Stack Overflow questions.
- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb-lightning/issues?q=is%3Aissue)
- Read the documentation:
    * [Detailed documentation](https://pingcap.com/docs/tools/lightning/overview-architecture/)
    * [简体中文文档](https://pingcap.com/docs-cn/tools/lightning/overview-architecture/) 

I had read doc and search the code , so I found out these:

https://github.com/pingcap/docs-cn/blob/master/tidb-lightning/tidb-lightning-table-filter.md#L64-L66

https://github.com/pingcap/tidb-lightning/blob/391db4a233a870fc2044494caa770da791f49734/lightning/config/config.go#L436-L441

But I want to know why we has hardcode to setting block system database and how could we import the `mysql` database using lightning.

**Comment by kennytm** [comment]
The `mysql` schema contained data which the database system relied on. Directly bringing system information from MySQL to TiDB may break it since there is no compatibility guarantee of these table. 

The `mysql` schema is filtered because the `mydumper` output may be polluted by these system schemas when no filtering was used. Currently there is no plan to lift the restriction.

If you really need to import `mysql.*` (understanding the risks), you could still use the traditional restore method:

```sh
mysql -u root -h 127.0.0.1 -P 4000 < mysql.db.sql
mysql -u root -h 127.0.0.1 -P 4000 < mysql.table_priv.sql
...
```

**Comment by shonge** [comment]
I get it , thanks.
