### ISSUE TITLE
lightning restore fail to restore csv with special delimiter

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb-lightning#519]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
run lightning with following configuration:
```toml
[mydumper.csv]
separator = ','
delimiter = "'"
header = true
not-null = false
null = '\N'
backslash-escape = false
trim-last-separator = false
```
to restore csv file:
```csv
'a','b'
'''','"'
'"',''''''
'''''','""'
'""','''"'''
'''"''','"''''''"''"'
'"''''''''"''"','"''"''''''''''"'
'"''"''"''''''''"',''
'a",b,"a','a,"c",a'
'bbaa|*|aabb','bba|*|a|*|abb'
```

2. What did you expect to see?
The original data in SQL format is:
```sql
/*!40101 SET NAMES binary*/;
INSERT INTO `escape` VALUES
('''', '"'),
('"', ''''''),
('''''', '""'),
('""', '''"'''),
('''"''', '"''''''"''"'),
('"''''''''"''"', '"''"''''''''''"'),
('"''"''"''''''''"', ''),
('a",b,"a', 'a,"c",a'),
('bbaa|*|aabb', 'bba|*|a|*|abb');
```
In TiDB, it looks like:
```sql
mysql> select * from escape;
+-------------+---------------+
| a           | b             |
+-------------+---------------+
| '           | "             |
| "           | ''            |
| ''          | ""            |
| ""          | '"'           |
| '"'         | "'''"'"       |
| "''''"'"    | "'"'''''"     |
| "'"'"''''"  |               |
| a",b,"a     | a,"c",a       |
| bbaa|*|aabb | bba|*|a|*|abb |
+-------------+---------------+
```

3. What did you see instead?
The restoration succeed and tidb-lightning didn't report an error. 
After restoration, the data in TiDB is:
```sql
mysql> select * from escape;
+-------------+---------------+
| a           | b             |
+-------------+---------------+
| "           | "             |
| "           | ""            |
| ""          | ""            |
| ""          | """           |
| """         | """""""       |
| """"""""    | """""""""     |
| """"""""""  |               |
| a",b,"a     | a,"c",a       |
| bbaa|*|aabb | bba|*|a|*|abb |
+-------------+---------------+
```

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        Release Version: v3.0.16-95-ga0b12ac
        Git Commit Hash: a0b12acea7bce946a50cf0bbd5edc9b0990703b4
        Git Branch: master
        UTC Build Time: 2020-12-09 12:20:15
        Go Version: go version go1.13.4 darwin/amd64
        ```
        
    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        Release Version: v4.0.0
        Edition: Community
        Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
        Git Branch: HEAD
        UTC Build Time: 2020-05-28 11:09:45
        GoVersion: go1.13.4
        Race Enabled: false
        TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
        Check Table Before Drop: false
        ```

**Comment by kennytm** [comment]
Affected versions: [v3.0.13:v3.0.19], [v4.0.0:v4.0.8]

**Comment by kennytm** [comment]
**1. Root Cause Analysis (RCA)**

The CSV parser code incorrectly assumed the delimiter is always either empty or `"`, and hard-coded the character `"` during unescaping.

**2. Symptom**

The data inserted, if containing the delimiter string, is always replaced by `"`

**3. All Trigger Conditions**

All of:

1. Using Lightning to import CSV files
2. The setting `mydumper.csv.delimiter` is set to any string other than `''` (empty) or `'"'` (double quote)
3. The CSV file used doubling to escape the delimiter.

Example: Setting delimiter to `'$'` and then used `$abc$$def$` in the CSV file. The bug will cause `abc"def` instead of the correct `abc$def` to be imported.

**4. Workaround**

If Lightning was used to import CSV files, *and* the delimiter is set to anything other than `'"'` (the default) or `''`, search for any occurrences of doubling to determine if the data is affected.

If the data is already imported, search for existence of the `"` character and manually determine if it is correct.

```sql
SELECT * FROM tbl WHERE text_col_1 LIKE '%"%' OR text_col_2 LIKE '%"%' OR ...;
```

When exporting, always use `"` as the delimiter (a.k.a. `FIELDS ENCLOSED BY`), and prefer to enable backslash escapes (a.k.a. `FIELDS ESCAPED BY '\\'`, typically enabled by default).

**5. Affected versions**

[v3.0.13:v3.0.19], [v4.0.0:v4.0.8]

**6. Fixed versions**

v3.0.20, v4.0.9
